# Generated by Django 3.1.2 on 2020-10-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='usertype',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
