# Generated by Django 3.1.2 on 2020-10-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0002_myuser_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
