# Generated by Django 3.1.2 on 2020-10-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0003_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AlterField(
            model_name='signup',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
