# Generated by Django 3.1.2 on 2020-10-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0004_auto_20201007_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CollegeQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('col_question', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_answer', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_question', models.CharField(max_length=250)),
            ],
        ),
        migrations.DeleteModel(
            name='myUser',
        ),
        migrations.AddField(
            model_name='facultyanswer',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentfeedback.facultyquestion'),
        ),
        migrations.AddField(
            model_name='collegeanswer',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentfeedback.collegequestion'),
        ),
    ]
