# Generated by Django 3.1.2 on 2020-10-07 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0005_auto_20201007_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegeanswer',
            old_name='faculty',
            new_name='college',
        ),
    ]
