# Generated by Django 3.1.2 on 2020-10-07 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0006_auto_20201007_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultyanswer',
            name='faculty',
        ),
        migrations.DeleteModel(
            name='CollegeAnswer',
        ),
        migrations.DeleteModel(
            name='CollegeQuestion',
        ),
        migrations.DeleteModel(
            name='FacultyAnswer',
        ),
        migrations.DeleteModel(
            name='FacultyQuestion',
        ),
    ]
