# Generated by Django 3.1.2 on 2020-10-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0007_auto_20201008_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('facans1', models.CharField(max_length=200)),
                ('facans2', models.CharField(max_length=200)),
                ('facans3', models.CharField(max_length=200)),
                ('facans4', models.CharField(max_length=200)),
            ],
        ),
    ]
