# Generated by Django 3.1.2 on 2020-10-14 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0010_auto_20201015_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RemoveField(
            model_name='facultyanswer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facultyanswer',
            name='facans1',
        ),
        migrations.RemoveField(
            model_name='facultyanswer',
            name='facans2',
        ),
        migrations.RemoveField(
            model_name='facultyanswer',
            name='facans3',
        ),
        migrations.RemoveField(
            model_name='facultyanswer',
            name='facans4',
        ),
        migrations.AddField(
            model_name='facultyanswer',
            name='ans_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='FacultyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que_text', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentfeedback.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='facultyanswer',
            name='question',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='studentfeedback.facultyquestion'),
        ),
    ]
