# Generated by Django 3.1.2 on 2020-10-14 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0011_auto_20201015_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyanswer',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='studentfeedback.facultyquestion'),
        ),
    ]
