# Generated by Django 3.1.2 on 2020-11-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0015_auto_20201109_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='faculty_QA_2',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signup',
            name='faculty_QA_3',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signup',
            name='faculty_QA_4',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signup',
            name='faculty_QA_5',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signup',
            name='faculty_QA_6',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='signup',
            name='faculty_QA_7',
            field=models.CharField(blank=True, default='', max_length=5000),
        ),
    ]
