# Generated by Django 3.1.2 on 2020-11-19 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentfeedback', '0016_auto_20201109_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='collegequestion',
            name='ans11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='ans12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='ans13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='ans14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='ans15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='que11',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='que12',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='que13',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='que14',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='collegequestion',
            name='que15',
            field=models.CharField(default='', max_length=200),
        ),
    ]
